### ISSUE TITLE
Peds wont spawn

### ISSUE THREAD

**Issue by vanemp21** [LukeWasTakenn/luke_tourguide#1]
All its fine, I can take the job, spawn car, go to the side, but when I go to the side and press E nothing happens. Don't spawn any ped. I put all dependencys and in order as you said. Am I doing something wrong? Need I change something about ped config? I'm in localhost so I'm not using anticheat.

**Comment by LukeWasTakenn** [comment]
Hey, do you get any errors in the console (F8) or maybe in the server console when the peds are supposed to spawn?

**Comment by vanemp21** [comment]
0 errors in F8 and console

**Comment by LukeWasTakenn** [comment]
Can you please try going to the line number 376 and change the 50 in Citizen.Wait() to something like a 100 or 200, this will slow down the rate the models load at, but that might be the issue in this case. Also does the route blip spawn on the map after you 'pick up the tourists'?

**Comment by vanemp21** [comment]
yes, the route its fine, only dont spawn npcs when I arrive https://streamable.com/5u4e0d . I'm going to try your tip.

**Comment by LukeWasTakenn** [comment]
Oh I see. This isn't about the peds loading, for some reason your input isn't being detected by the script.

**Comment by vanemp21** [comment]
I tried your tip and changing the key to 57 (F10) but nothing happens :/

**Comment by LukeWasTakenn** [comment]
Hm, I don't think there's generally much I can do about this, it could honestly be a million things. Make sure your server artifact version is up to date. You can also add a print at line 214 after the if statement to see if the code even gets to that point, because to me it seems like that is the issue.

**Comment by vanemp21** [comment]
Hmm, its printing so maybe its my fault, thanks anyway for your help. I'm going to check what happens

**Comment by vanemp21** [comment]
Omg I'm really retarded, I solved it. The dependency its **pog**ressBar not **prog**ressBars . I read bad, now works, sorry for the inconvenence

**Comment by LukeWasTakenn** [comment]
No worries mate, I'm glad you got it solved. To be fair maybe I should've used events instead of exports, I think that would've thrown you an error at least. I hope you enjoy the script :)

**Comment by vanemp21** [comment]
I love it, thanks so much for create it
